feat: make wadcheck functional

diff --git a/src/wad b/src/wad
--- a/src/wad
+++ b/src/wad
@@ -9,25 +9,20 @@ set -o pipefail
 IFS=$'\n\t'
 LANG=C
 
-declare -A dir
+NAME="$(basename "$0")"
+VERSION="${DOOM_UTILS_VERSION:-"dev"}"
+
+DATA_DIR="${XDG_DATA_HOME:="${HOME}/.local/share"}"
+
 declare -A sha1
 
-dir_data="${XDG_DATA_HOME:="${HOME}/.local/share"}"
-dir_main="${DOOMWADDIR:="${dir_data}/games/doom"}"
-
-dir["doom_2"]="${dir_main}/doom2.wad"
-dir["doom_1"]="${dir_main}/doom1.wad"
-
-dir["nrftl"]="${dir_main}/nrftl.wad"
-dir["sigil_1"]="${dir_main}/sigil1.wad"
-dir["sigil_2"]="${dir_main}/sigil2.wad"
-
-sha1["iwad_doom_2"]="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7"
-sha1["iwad_doom_1"]="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833"
-
-sha1["ewad_nrftl"]="3451288383fb16e196f273d9f85d58c1fda97bf4"
-sha1["ewad_sigil_1"]="e2efdf379e1383c4e15c03de89063361897cd459"
-sha1["ewad_sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4"
+sha1["doom_2"]="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7"
+sha1["doom_1"]="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833"
+sha1["tnt"]="9fbc66aedef7fe3bae0986cdb9323d2b8db4c9d3"
+sha1["plutonia"]="90361e2a538d2388506657252ae41aceeb1ba360"
+sha1["nerve"]="3451288383fb16e196f273d9f85d58c1fda97bf4"
+sha1["sigil_1"]="e2efdf379e1383c4e15c03de89063361897cd459"
+sha1["sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4"
 
 check()
 {
@@ -56,4 +51,46 @@ check()
 
 	return 0
 }
+
+function print_help()
+{
+	echo "Usage: ${NAME} [OPTIONS]"
+	echo "Options:"
+	echo "    -h  Print this help message"
+	echo "    -v  Print version information"
+	echo ""
+	exit 0
+
+}
+
+function print_version()
+{
+	echo "${NAME} - DoomUtils ${VERSION}"
+	exit 0
+}
+
+function main()
+{
+	while getopts ":hv" option; do
+		case "${option}" in
+			h)
+				print_help
+				;;
+			v)
+				print_version
+				;;
+			\?)
+				echo "Option -${OPTARG} is invalid" >&2
+				exit 1
+				;;
+			:)
+				echo "Option -${OPTARG} requires an argument" >&2
+				exit 1
+				;;
+		esac
+	done
+	check
+}
+
+main "$@"
 
