chore: improved formatting
added seperate logging functions

diff --git a/src/wad b/src/wad
--- a/src/wad
+++ b/src/wad
@@ -1,104 +1,123 @@
 #!/usr/bin/env bash
 
-# Bash's unofficial strict mode
-set -euo pipefail
+# Bash strict mode
+set -o errtrace;
+set -o errexit;
+set -o nounset;
+set -o pipefail;
+IFS=$'\n\t'
 
-dir_data="${XDG_DATA_HOME:="$HOME/.local/share"}"
+dir_data="${XDG_DATA_HOME:="$HOME/.local/share"}";
 
-dir_main="$dir_data/doom-utils"
+dir_main="$dir_data/doom-utils";
 
-dir_iwad="$dir_main/iwad"
-dir_ewad="$dir_main/ewad"
+dir_iwad="$dir_main/iwad";
+dir_ewad="$dir_main/ewad";
 
-iwad_doom_2="$dir_iwad/doom2.wad"
-iwad_doom_1="$dir_iwad/doom1.wad"
+iwad_doom_2="$dir_iwad/doom2.wad";
+iwad_doom_1="$dir_iwad/doom1.wad";
 
-ewad_nerve="$dir_ewad/nerve.wad"
-ewad_sigil_1="$dir_ewad/sigil1.wad"
-ewad_sigil_2="$dir_ewad/sigil2.wad"
+ewad_nerve="$dir_ewad/nerve.wad";
+ewad_sigil_1="$dir_ewad/sigil1.wad";
+ewad_sigil_2="$dir_ewad/sigil2.wad";
 
-iwad_doom_2_sha1="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7"
-iwad_doom_1_sha1="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833"
+iwad_doom_2_sha1="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7";
+iwad_doom_1_sha1="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833";
 
-ewad_nerve_sha1="3451288383fb16e196f273d9f85d58c1fda97bf4"
-ewad_sigil_2_sha1="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4"
-ewad_sigil_1_sha1="e2efdf379e1383c4e15c03de89063361897cd459"
+ewad_nerve_sha1="3451288383fb16e196f273d9f85d58c1fda97bf4";
+ewad_sigil_2_sha1="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4";
+ewad_sigil_1_sha1="e2efdf379e1383c4e15c03de89063361897cd459";
+
+success() {
+    echo "[ Success ] $1";
+}
+
+info() {
+    echo "[ Info ] $1";
+}
+
+warn() {
+    echo "[ Warn ] $1";
+}
+
+error() {
+    echo "[ Error ] $1";
+}
 
 check_steam_directory() {
-    echo "[ Info ] Checking Steam directory."
+    info "Checking Steam directory.";
 
     if ! [ -d "$dir_data/Steam" ]; then
-	echo "[ Error ] Steam directory does exit, have you installed it on the $XDG_DATA_HOME?"
-	exit 1
+	error "Steam directory does exit, have you installed it on the $XDG_DATA_HOME?";
+	exit 1;
     fi
 
-    echo "[ Success ] Steam directory found."
+    success "Steam directory found.";
     return 0
 }
 
 check_doom_1_directory() {
-    echo "[ Info ] Checking Doom installation."
+    info "Checking Doom installation.";
 
     if ! [ -d "$dir_data/Steam/steamapps/common/Ultimate Doom" ]; then
-	echo "[ Error ] Could not find Ultimate Doom intallation."
-	echo "[ Error ] Check your Ultimate Doom installation on the Steam Client."
-	echo "[ Error ] Make sure to install in your \$XDG_DATA_HOME"
-	return 1
-    fi
+	error "Could not find Ultimate Doom intallation.";
+	error "Check your Ultimate Doom installation on the Steam Client.";
+	error "Make sure to install in your \$XDG_DATA_HOME";
+	return 1;
+    fi;
 
-    echo "[ Success ] Ultimate Doom steam installation found."
-    return 0
+    success "Ultimate Doom steam installation found.";
+    return 0;
 }
 
 check_doom_2_directory() {
-    echo "[ Info ]: Checking Doom 2 installation."
+    info "Checking Doom 2 installation."
 
     if ! [ -d "$dir_data/Steam/steamapps/common/Doom 2" ]; then
-	echo "[ Error ] Could not find Doom 2 intallation."
-	echo "[ Error ] Check your Doom 2 installation on the Steam Client."
-	echo "[ Error ] Make sure to install in your \$XDG_DATA_HOME"
-	return 1
-    fi
+	error "Could not find Doom 2 intallation.";
+	error "Check your Doom 2 installation on the Steam Client.";
+	error "Make sure to install in your \$XDG_DATA_HOME";
+	return 1;
+    fi;
 
-    echo "[ Success ] Doom 2 steam installation found."
-    return 0
+    success "Doom 2 steam installation found.";
+    return 0;
 }
 
-main-help() {
-    echo "Help"
-    return 0
+help() {
+    echo "Help";
+    return 0;
 }
 
-main-find() {
-    check_steam_directory
-    check_doom_1_directory
-    check_doom_2_directory
-    return 0
+find() {
+    check_steam_directory;
+    check_doom_1_directory;
+    check_doom_2_directory;
+    return 0;
 }
 
-main-list() {
-    ls "$dir_main"
+list() {
+    if ! [ -d "$dir_main" ]; then mkdir -p "$dir_main" ; fi;
+    ls -l "$dir_main";
+    return 0;
 }
 
 main() {
+    if [ $# -eq 0 ]; then return 1; fi;
+
     case "$1" in
 	find)
-	    echo "[ Info ] Finding wads"
-	    main-find "${@:2}"
+	    find "${@:2}";
 	    ;;
 	list)
-	    echo "[ Info ] Listing wads"
-	    main-list "${@:2}"
-	    ;;
-	help)
-	    main-help "${@:2}"
+	    list "${@:2}";
 	    ;;
 	*)
-	    echo "wtf: $1"
+	    help "${@:2}";
 	    ;;
-    esac
-    return 0
+    esac;
+    return 0;
 }
 
-main "$@"
+main "$@";
 
