fix: Minor organization.

diff --git a/src/wad b/src/wad
--- a/src/wad
+++ b/src/wad
@@ -28,6 +28,7 @@ ewad_nerve_sha1="3451288383fb16e196f273d9f85d58c1fda97bf4";
 ewad_sigil_2_sha1="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4";
 ewad_sigil_1_sha1="e2efdf379e1383c4e15c03de89063361897cd459";
 
+# Here be util commands
 success() {
     echo "[ Success ] $1";
 }
@@ -44,55 +45,42 @@ error() {
     echo "[ Error ] $1";
 }
 
-check_steam_directory() {
-    info "Checking Steam directory.";
-
-    if ! [ -d "$dir_data/Steam" ]; then
-	error "Steam directory does exit, have you installed it on the $XDG_DATA_HOME?";
-	exit 1;
-    fi
-
-    success "Steam directory found.";
-    return 0
-}
-
-check_doom_1_directory() {
-    info "Checking Doom installation.";
-
-    if ! [ -d "$dir_data/Steam/steamapps/common/Ultimate Doom" ]; then
-	error "Could not find Ultimate Doom intallation.";
-	error "Check your Ultimate Doom installation on the Steam Client.";
-	error "Make sure to install in your \$XDG_DATA_HOME";
-	return 1;
-    fi;
-
-    success "Ultimate Doom steam installation found.";
-    return 0;
-}
-
-check_doom_2_directory() {
-    info "Checking Doom 2 installation."
-
-    if ! [ -d "$dir_data/Steam/steamapps/common/Doom 2" ]; then
-	error "Could not find Doom 2 intallation.";
-	error "Check your Doom 2 installation on the Steam Client.";
-	error "Make sure to install in your \$XDG_DATA_HOME";
-	return 1;
-    fi;
-
-    success "Doom 2 steam installation found.";
-    return 0;
-}
-
+# Here be subcommands
 help() {
     echo "Help";
     return 0;
 }
 
 find() {
-    check_steam_directory;
-    check_doom_1_directory;
-    check_doom_2_directory;
+    info "Checking Steam directory.";
+
+    if ! [ -d "$dir_data/Steam" ]; then
+        error "Steam directory does exit, have you installed it on the $XDG_DATA_HOME?";
+        exit 1;
+    fi
+
+    success "Steam directory found.";
+
+    info "Checking Doom installation.";
+
+    if ! [ -d "$dir_data/Steam/steamapps/common/Ultimate Doom" ]; then
+        error "Could not find Ultimate Doom intallation.";
+        error "Check your Ultimate Doom installation on the Steam Client.";
+        error "Make sure to install in your \$XDG_DATA_HOME";
+    fi;
+
+    success "Ultimate Doom steam installation found.";
+
+    info "Checking Doom 2 installation."
+
+    if ! [ -d "$dir_data/Steam/steamapps/common/Doom 2" ]; then
+        error "Could not find Doom 2 intallation.";
+        error "Check your Doom 2 installation on the Steam Client.";
+        error "Make sure to install in your \$XDG_DATA_HOME";
+    fi;
+
+    success "Doom 2 steam installation found.";
+
     return 0;
 }
 
@@ -106,18 +94,17 @@ main() {
     if [ $# -eq 0 ]; then return 1; fi;
 
     case "$1" in
-	find)
-	    find "${@:2}";
-	    ;;
-	list)
-	    list "${@:2}";
-	    ;;
-	*)
-	    help "${@:2}";
-	    ;;
+    find)
+        find "${@:2}";
+        ;;
+    list)
+        list "${@:2}";
+        ;;
+    *)
+        help "${@:2}";
+        ;;
     esac;
     return 0;
 }
 
 main "$@";
-
