style: Streamlined code formatting

diff --git a/src/wad b/src/wad
--- a/src/wad
+++ b/src/wad
@@ -13,43 +13,37 @@ declare -A ewad;
 declare -A sha1;
 
 dir_data="${XDG_DATA_HOME:="$HOME/.local/share"}";
+dir_main="$dir_data/doom-utils"
 
-dir["main"]="$dir_data/doom-utils";
-dir["iwad"]="$dir_data/doom-utils/iwad";
-dir["ewad"]="$dir_data/doom-utils/ewad";
+dir["main"]="$dir_main";
+dir["iwad"]="$dir_main/iwad";
+dir["ewad"]="$dir_main/ewad";
 
-iwad["doom_2"]="$dir_data/doom-utils/iwad/doom2.wad";
-iwad["doom_1"]="$dir_data/doom-utils/iwad/doom1.wad";
+iwad["doom_2"]="$dir_main/iwad/doom2.wad";
+iwad["doom_1"]="$dir_main/iwad/doom1.wad";
 
-ewad["nerve"]="$dir_data/doom-utils/ewad/nerve.wad";
-ewad["sigil_1"]="$dir_data/doom-utils/ewad/sigil1.wad";
-ewad["sigil_2"]="$dir_data/doom-utils/ewad/sigil2.wad";
+ewad["nerve"]="$dir_main/ewad/nerve.wad";
+ewad["sigil_1"]="$dir_main/ewad/sigil1.wad";
+ewad["sigil_2"]="$dir_main/ewad/sigil2.wad";
 
 sha1["iwad_doom_2"]="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7";
 sha1["iwad_doom_1"]="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833";
 
 sha1["ewad_nerve"]="3451288383fb16e196f273d9f85d58c1fda97bf4";
-sha1["ewad_sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4";
 sha1["ewad_sigil_1"]="e2efdf379e1383c4e15c03de89063361897cd459";
+sha1["ewad_sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4";
 
 supports_color () {
     if command -v tput > /dev/null; then
-        if [[ "$(tput colors)" -ge 8 ]]; then
-            return 0;
-        fi;
+        if [[ "$(tput colors)" -ge 8 ]]; then return 0; fi;
     elif [[ -n "$TERM" ]]; then
-        case "$TERM" in
-            (xterm|xterm-256color|rxvt|screen*)
-                return 0;
-                ;;
-        esac;
+        case "$TERM" in (xterm|xterm-256color|rxvt|screen*) return 0; esac;
     fi;
     return 1;
 }
 
 if supports_color; then
-    # Basic colors
-    RESET="\e[0m";
+    # Color modifiers;
     FG_BLACK="\e[30m";
     FG_RED="\e[31m";
     FG_GREEN="\e[32m";
@@ -58,11 +52,12 @@ if supports_color; then
     FG_MAGENTA="\e[35m";
     FG_CYAN="\e[36m";
     FG_WHITE="\e[37m";
-    # Other text modifiers;
+    # Non-color modifiers;
+    RESET="\e[0m";
     BOLD="\e[1m";
     UNDERLINE="\e[4m";
 else
-    RESET="";
+    # Color modifiers;
     FG_BLACK="";
     FG_RED="";
     FG_GREEN="";
@@ -71,30 +66,31 @@ else
     FG_MAGENTA="";
     FG_CYAN="";
     FG_WHITE="";
-    # Other text modifiers;
+    # Non-color modifiers;
+    RESET="";
     BOLD="";
     UNDERLINE="";
 fi;
 
 success() {
-    echo -e "${FG_GREEN}Success${RESET} $1";
+    echo -e "${FG_GREEN}Success${RESET} $1" >&1;
 }
 
 info() {
-    echo -e "${FG_BLUE}Info${RESET} $1";
+    echo -e "${FG_BLUE}Info${RESET} $1" >&1;
 }
 
 warn() {
-    echo -e "${FG_YELLOW}Warn${RESET} $1";
+    echo -e "${FG_YELLOW}Warn${RESET} $1" >&2;
 }
 
 error() {
-    echo -e "${FG_RED}Error${RESET} $1";
+    echo -e "${FG_RED}Error${RESET} $1" >&2;
 }
 
 # Here be subcommands
 help() {
-    echo "Help";
+    echo "Help" >&1;
     return 0;
 }
 
@@ -103,7 +99,7 @@ find() {
 
     if ! [[ -d "$dir_data/Steam" ]];
         then
-            error "Steam directory does exit, have you installed it on the $XDG_DATA_HOME?";
+            error "Steam directory does exit, have you installed it on the \$XDG_DATA_HOME?";
             exit 1;
         else
             success "Steam directory found.";
