fix: clear error and success messages

diff --git a/src/wadcheck b/src/wadcheck
--- a/src/wadcheck
+++ b/src/wadcheck
@@ -24,29 +24,28 @@ sha1["nerve"]="3451288383fb16e196f273d9f85d58c1fda97bf4"
 sha1["sigil_1"]="e2efdf379e1383c4e15c03de89063361897cd459"
 sha1["sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4"
 
-check()
+function check()
 {
-	if ! [[ -d "${dir_data}/Steam" ]]; then
-		error "Steam directory does exit, have you installed it on the \$XDG_DATA_HOME?"
+	if ! [[ -d "${DATA_DIR}/Steam" ]]; then
+		echo "Steam directory does not exit\n"\
+		"Have you installed it on the \$XDG_DATA_HOME?\n" >&2
 		exit 1
 	else
-		success "Steam directory found."
+		echo "Steam directory found."
 	fi
 
-	if ! [[ -d "${dir_data}/Steam/steamapps/common/Ultimate Doom" ]]; then
-		error "Could not find Ultimate Doom intallation."
-		error "Check your Ultimate Doom installation on the Steam Client."
-		error "Make sure to install in your \$XDG_DATA_HOME"
+	if ! [[ -d "${DATA_DIR}/Steam/steamapps/common/Ultimate Doom" ]]; then
+		echo "Could not find Ultimate Doom intallation.\n"\
+		"Check your Ultimate Doom installation on the Steam Client.\n" >&2
 	else
-		success "Ultimate Doom steam installation found."
+		echo "Ultimate Doom steam installation found."
 	fi
 
-	if ! [[ -d "${dir_data}/Steam/steamapps/common/Doom 2" ]]; then
-		error "Could not find Doom 2 intallation."
-		error "Check your Doom 2 installation on the Steam Client."
-		error "Make sure to install in your \$XDG_DATA_HOME"
+	if ! [[ -d "${DATA_DIR}/Steam/steamapps/common/Doom 2" ]]; then
+		echo "Could not find Doom 2 intallation.\n"\
+		"Check your Doom 2 installation on the Steam Client.\n" >&2
 	else
-		success "Doom 2 steam installation found."
+		echo "Doom 2 steam installation found."
 	fi
 
 	return 0
